default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: imroz
  password: password
  host: localhost

development:
  <<: *default
  database: my_auth_api_development

test:
  <<: *default
  database: my_auth_api_test

production:
  <<: *default
  database: my_auth_api_production
  username: postgres
  password: your_production_password
  host: your_production_host # Change if deploying to a cloud DB
